### PR TITLE
Detect when virtualTypes move elsewhere

### PR DESCRIPTION
**Pull request by fredden**
# Description

While working on https://github.com/magento/magento2/pull/32690, it was noticed that a `virtualType` which is used in multiple modules (namely `shellBackground` used in both `Magento_Cron` and `Magento_MessageQueue`). Moving this to `app/etc/di.xml` where it belongs triggered an automated test failure from this tool. This pull request aims to handle this case as expected.

## Manual testing scenarios

Unit tests are included with this change. Without the code change, these unit tests fail.

## Contribution checklist

- [x] Pull request has a meaningful description of its purpose
- [x] All commits are accompanied by meaningful commit messages
- [x] All new or changed code is covered with unit/integration tests (if applicable)
- [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by ihor-sviziev — APPROVED** [review]

**Comment by ihor-sviziev** [comment]
@sidolov please merge this pull request

**Comment by engcom-Charlie** [comment]
@sidolov can you please merge this PR. https://github.com/magento/magento2/pull/32690 is depended on this PR.

**Review by sidolov — APPROVED** [review]

**Comment by sidolov** [comment]
@magento import pr to magento-commerce/magento-semver repository

**Comment by m2-github-services** [comment]
@sidolov the Pull Request is successfully imported.

**Pull request merged**
