### PR TITLE
![Arrows] MC-36802: SVC doesn't catch MINOR change in PATCH release when adding @api to a class

### PR DESCRIPTION
**Pull request by zakdma**
### Bug - P1
* [MC-36802](https://jira.corp.magento.com/browse/MC-36802) SVC doesn't catch MINOR change in PATCH release when adding @api to a class

Created by : @zakdma

### CODE REVIEW

**Comment by zakdma** [comment]
@roribio @vkublytskyi please review this PR

**Comment by vkublytskyi** [comment]
@maghamed, please confirm that from an architectural point of view this [is desired behavior](https://github.com/magento/magento-semver/pull/55/files#diff-0f17bac717ac9d540e75a61def93a9da):
- `@api` annotation added - minor change
- `@api` annotation removed - minor change

**Comment by maghamed** [comment]
Why do we consider that api annotation removal is Minor but not a Major change?

**Comment by zakdma** [comment]
@vkublytskyi @maghamed 
@api removal classification changed to major

**Review by vkublytskyi — DISMISSED** [review]

**Review by vkublytskyi — APPROVED** [review]

**Review by vkublytskyi — APPROVED** [review]

**Comment by okorshenko** [comment]
@magento import pull request to https://github.com/magento-tsg/magento-semver

**Comment by sidolov** [comment]
@magento import pull request to https://github.com/magento-tsg/magento-semver

**Comment by magento-engcom-team** [comment]
@sidolov, an error occurred during the Pull Request import.

**Comment by zakdma** [comment]
Closed in favor of
https://github.com/magento-commerce/magento-semver/pull/11

**Pull request closed without merging**
